### ISSUE TITLE
The "New Scratchpad" search bar should sort filtered results by extension, then file type.

### ISSUE THREAD

**Issue by DanKaplanSES** [buenon/scratchpads#40]
This is a minor feature request that, IMHO, would improve developer experience. Here are steps to reproduce:

1. Open the "New Scratchpad" search bar
2. Type `txt`

Expected: the first result should be `Text (.txt)`
Actual: the first result is `TEXI (.texi)`

## Screenshot:

![image](https://github.com/buenon/scratchpads/assets/373675/bfd7bc6d-37fe-4d4a-a4b4-85e4b9ce4300)

## Workaround:

- Typing `.txt` instead of `txt` filters as expected. 
- Alternatively, you can select from the filtered list.

Considering the workarounds, these are minor inconveniences, but it adds up throughout the day. And for me at least, this is unexpected behavior.

**Comment by buenon** [comment]
This issue is more complex than it initially appears.
Once the user begins typing in the search bar, VS Code automatically handles filtering and sorting, without providing an option to override this functionality.
Even when attempting to implement manual filtering and sorting using onDidChangeValue, VS Code continues to apply its own filtering and sorting logic, overriding custom behavior.
I’ll go ahead and close this issue, but if VS Code introduces relevant API changes in the future, I’d be happy to revisit this.

**Comment by DanKaplanSES** [comment]
Would it work if you were to rearrange the drop-down text so that the extension came before the file type?

**Comment by buenon** [comment]
> Would it work if you were to rearrange the drop-down text so that the extension came before the file type?

Tried that as well.
The behavior was still inconsistent.
